### ISSUE TITLE
Crash using JOML classes

### ISSUE THREAD

**Issue by CrowsOfWar** [CrowsOfWar/AvatarMod#10]
JOML library wasn't put into the JAR. This causes any code using JOML to crash. Solution: make a fat JAR (can legally redistribute JOML binaries)

Relevant stacktrace:
```
java.lang.NoClassDefFoundError: org/joml/Matrix4d
at com.crowsofwar.avatar.client.render.RenderArc.renderSegment(RenderArc.java:100)
at com.crowsofwar.avatar.client.render.RenderArc.func_76986_a(RenderArc.java:52)
at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:623)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1381)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
```

**Comment by CrowsOfWar** [comment]
Fixed by f70e6b8.
